version: '3.9'
services:
  keepass-web:
    build: .
    ports:
      - '8080:80'
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'wget', '-q', '--spider', 'http://localhost/']
      interval: 30s
      timeout: 3s
      retries: 3
